services:
  - type: web
    name: volatix-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    autoDeploy: true
